FROM alpine:3.3
MAINTAINER Donagh Horgan <donagh.horgan@gmail.com>

RUN apk --no-cache add ca-certificates

ENV DOCKERIZE_VERSION v0.2.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

ENTRYPOINT ["/usr/local/bin/dockerize", "-wait"]
